In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('all_feature_significance_summary.csv')

In [3]:
df

,feature,dataset,target,stance,source,t_pvalue,u_pvalue,cohens_d,cliffs_delta,cohen_strength,cliff_strength,distributions_normal,preferred_effect,preferred_strength,significant
0,word_count,whole,ALL,AGAINST,whole,0.0100,0.0042,0.2504,0.1628,small,small,False,Cliff's delta,small,yes
1,sentence_count,whole,ALL,AGAINST,whole,0.2578,0.3882,0.1024,0.0473,small,negligible,False,Cliff's delta,negligible,no
2,avg_word_length,whole,ALL,AGAINST,whole,0.2192,0.5437,0.1146,0.0345,small,negligible,False,Cliff's delta,negligible,no
3,std_word_length,whole,ALL,AGAINST,whole,0.1601,0.0524,-0.1291,-0.1102,small,negligible,False,Cliff's delta,negligible,no
4,type_token_ratio,whole,ALL,AGAINST,whole,0.6392,0.6473,-0.0453,-0.0260,small,negligible,False,Cliff's delta,negligible,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,C_ratio,semeval,Hillary Clinton,NONE,target,0.5317,0.2840,0.2670,0.1591,small,small,False,Cliff's delta,small,no
1580,D_ratio,semeval,Hillary Clinton,NONE,target,NaN,1.0000,0.0000,0.0000,small,negligible,True,Cohen's d,small,no
1581,E_ratio,semeval,Hillary Clinton,NONE,target,0.8547,0.5153,-0.0686,-0.0739,small,negligible,False,Cliff's delta,negligible,no
1582,I_ratio,semeval,Hillary Clinton,NONE,target,NaN,1.0000,0.0000,0.0000,small,negligible,True,Cohen's d,small,no
1583,N_ratio,semeval,Hillary Clinton,NONE,target,0.4981,0.4479,-0.4127,-0.0852,medium,negligible,False,Cliff's delta,negligible,no

In [4]:
df_sig_only = df[df['significant']=='yes']
df_sig_only

,feature,dataset,target,stance,source,t_pvalue,u_pvalue,cohens_d,cliffs_delta,cohen_strength,cliff_strength,distributions_normal,preferred_effect,preferred_strength,significant
0,word_count,whole,ALL,AGAINST,whole,0.0100,0.0042,0.2504,0.1628,small,small,False,Cliff's delta,small,yes
7,punctuation_density,whole,ALL,AGAINST,whole,0.0043,0.0011,-0.2975,-0.1860,small,small,False,Cliff's delta,small,yes
18,subordinate_clause_ratio,whole,ALL,AGAINST,whole,0.0209,0.0680,0.2046,0.1022,small,negligible,False,Cliff's delta,negligible,yes
19,sentiment_polarity,whole,ALL,AGAINST,whole,0.0133,0.0041,-0.2471,-0.1609,small,small,False,Cliff's delta,small,yes
21,anger,whole,ALL,AGAINST,whole,0.0002,0.1967,0.2923,0.0734,small,negligible,False,Cliff's delta,negligible,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,joy,semeval,Hillary Clinton,NONE,target,0.0383,0.4751,0.5499,0.1818,medium,small,False,Cliff's delta,small,yes
1563,fear,semeval,Hillary Clinton,NONE,target,0.0000,0.0001,-2.1808,-0.8636,large,large,False,Cliff's delta,large,yes
1564,sadness,semeval,Hillary Clinton,NONE,target,0.0481,0.1176,0.5212,0.3864,medium,medium,False,Cliff's delta,medium,yes
1569,certainty_adjectives_count,semeval,Hillary Clinton,NONE,target,0.0425,0.2172,0.5318,0.1818,medium,small,False,Cliff's delta,small,yes
1570,doubt_adverbs_count,semeval,Hillary Clinton,NONE,target,0.0106,0.1119,0.6908,0.2727,medium,small,False,Cliff's delta,small,yes

In [5]:
df_new = pd.read_csv('all_feature_significanse_only.csv')
df_new

,feature,dataset,target,stance,source,t_pvalue,u_pvalue,cohens_d,cliffs_delta,cohen_strength,cliff_strength,distributions_normal,preferred_effect,preferred_strength,significant
0,word_count,whole,ALL,AGAINST,whole,0.0100,0.0042,0.2504,0.1628,small,small,False,Cliff's delta,small,yes
1,punctuation_density,whole,ALL,AGAINST,whole,0.0043,0.0011,-0.2975,-0.1860,small,small,False,Cliff's delta,small,yes
2,subordinate_clause_ratio,whole,ALL,AGAINST,whole,0.0209,0.0680,0.2046,0.1022,small,negligible,False,Cliff's delta,negligible,yes
3,sentiment_polarity,whole,ALL,AGAINST,whole,0.0133,0.0041,-0.2471,-0.1609,small,small,False,Cliff's delta,small,yes
4,anger,whole,ALL,AGAINST,whole,0.0002,0.1967,0.2923,0.0734,small,negligible,False,Cliff's delta,negligible,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,joy,semeval,Hillary Clinton,NONE,target,0.0383,0.4751,0.5499,0.1818,medium,small,False,Cliff's delta,small,yes
332,fear,semeval,Hillary Clinton,NONE,target,0.0000,0.0001,-2.1808,-0.8636,large,large,False,Cliff's delta,large,yes
333,sadness,semeval,Hillary Clinton,NONE,target,0.0481,0.1176,0.5212,0.3864,medium,medium,False,Cliff's delta,medium,yes
334,certainty_adjectives_count,semeval,Hillary Clinton,NONE,target,0.0425,0.2172,0.5318,0.1818,medium,small,False,Cliff's delta,small,yes
335,doubt_adverbs_count,semeval,Hillary Clinton,NONE,target,0.0106,0.1119,0.6908,0.2727,medium,small,False,Cliff's delta,small,yes